#!/bin/sh

if [ ! -d ~/.remmina ]; then
  echo ".remmina does not exist in your home directory"
  exit
fi

ping -c1 -W1 $1 > /dev/null 2>&1
if [ $? -ne 0 ]; then
   echo "Server $1 is not reachable"
   exit
fi

CONFIG=`grep -l "server=$1" ~/.remmina/*.remmina`
if [ $? -ne 0 ]; then
   echo "Server $1 is not available in your Remmina configurations"
   exit
fi

nohup remmina -c $CONFIG > /dev/null 2>&1 &
